# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_salesforce_forms', '0009_auto_20171017_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='custom_classes',
            field=models.CharField(blank=True, max_length=255, verbose_name='custom css classes'),
        ),
        migrations.AlterField(
            model_name='formplugin',
            name='form_name',
            field=models.CharField(blank=True, help_text='Optional. Used as the value of the hidden "Name of Form" field.', max_length=255, null=True, verbose_name='Name of Form'),
        ),
        migrations.AlterField(
            model_name='textfieldplugin',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('phone', 'Phone'), ('hidden', 'Hidden')], default='text', max_length=30, verbose_name='Type'),
        ),
    ]
