# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('aldryn_salesforce_forms', '0010_auto_20171109_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsetPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aldryn_salesforce_forms_fieldsetplugin', serialize=False, to='cms.CMSPlugin')),
                ('legend', models.CharField(blank=True, max_length=255, verbose_name='Legend')),
                ('custom_classes', models.CharField(blank=True, max_length=255, verbose_name='custom css classes')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
