# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_salesforce_forms', '0011_fieldsetplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldplugin',
            name='initial_value',
            field=models.CharField(blank=True, help_text='Default value of field.', max_length=255, verbose_name='Initial value'),
        ),
        migrations.AddField(
            model_name='textareafieldplugin',
            name='initial_value',
            field=models.CharField(blank=True, help_text='Default value of field.', max_length=255, verbose_name='Initial value'),
        ),
        migrations.AddField(
            model_name='textfieldplugin',
            name='initial_value',
            field=models.CharField(blank=True, help_text='Default value of field.', max_length=255, verbose_name='Initial value'),
        ),
    ]
