# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_salesforce_forms', '0012_auto_20171109_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='external_key',
            field=models.CharField(default='Form_Submission_Data', help_text='DEManager External Key to use for the submission (_deExternalKey field)', max_length=255, verbose_name='External Key'),
        ),
    ]
