# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 13:34
from __future__ import unicode_literals

from django.db import migrations
import djangocms_attributes_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_salesforce_forms', '0013_formplugin_external_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='formplugin',
            name='hidden_fields',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, help_text='Additional hidden fields to add to the form. (name/value)', verbose_name='Hidden Fields'),
        ),
    ]
