# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-10 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_salesforce_forms', '0014_formplugin_hidden_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formplugin',
            name='form_name',
        ),
    ]
