# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_salesforce_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='option',
            name='position',
            field=models.PositiveIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set([('field', 'position')]),
        ),
    ]
