# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:02
from __future__ import unicode_literals

from django.db import migrations, models


def forward_migration(apps, schema_editor):
    FieldPlugin = apps.get_model('djangocms_salesforce_forms', 'FieldPlugin')
    for field in FieldPlugin.objects.iterator():
        for idx, option in enumerate(field.option_set.order_by('value'), start=1):
            option.position = idx * 10
            option.save()


def backward_migration(apps, schema_editor):
    Option = apps.get_model('djangocms_salesforce_forms', 'Option')
    Option.objects.all().update(position=None)


class Migration(migrations.Migration):
    dependencies = [
        ('djangocms_salesforce_forms', '0001_initial'),
    ]

    operations = [
        # 1: create field as nullable
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='option',
            name='position',
            field=models.PositiveIntegerField(null=True, verbose_name='Position'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set([('field', 'position')]),
        ),

        # 2: populate field
        migrations.RunPython(forward_migration, backward_migration),

        # 3: update field to non-nullable
        migrations.AlterField(
            model_name='option',
            name='position',
            field=models.PositiveIntegerField(blank=True, verbose_name='Position'),
        ),

    ]
