# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_salesforce_forms', '0002_auto_20171124_1702'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set([]),
        ),
    ]
