# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-07 18:12
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_salesforce_forms', '0003_auto_20171129_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='page',
            field=cms.models.fields.PageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.Page', verbose_name='CMS Page'),
        ),
    ]
