# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_salesforce_forms', '0003_auto_20171129_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formplugin',
            name='redirect_type',
            field=models.CharField(blank=True, choices=[('redirect_to_page', 'CMS Page'), ('redirect_to_url', 'Absolute URL')], help_text='Where to redirect the user when the form has been successfully sent? Empty means "no redirect" (stays on same page, browser is not refreshed).', max_length=20, null=True, verbose_name='Redirect to'),
        ),
    ]
