# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models


def forward_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SalesforceFormPlugin = apps.get_model('djangocms_salesforce_forms', 'SalesforceFormPlugin')
    SalesforceFormPlugin.objects.using(db_alias).filter(action_backend='no_storage').update(action_backend='none')


def backward_migration(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SalesforceFormPlugin = apps.get_model('djangocms_salesforce_forms', 'SalesforceFormPlugin')
    SalesforceFormPlugin.objects.using(db_alias).filter(action_backend='none').update(action_backend='no_storage')


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_salesforce_forms', '0009_auto_20171222_0858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesforceformplugin',
            old_name='storage_backend',
            new_name='action_backend',
        ),

        migrations.AlterField(
            model_name='salesforceformplugin',
            name='action_backend',
            field=models.CharField(choices=[('default', 'Default'), ('email_only', 'Email only'), ('none', 'None')], default='default', max_length=15, verbose_name='Action backend'),
        ),

        migrations.RunPython(forward_migration, backward_migration),

    ]
